### ISSUE TITLE
Aria roles link broken

### ISSUE THREAD

**Issue by jsarkis** [FriendsOfEpub/eBookDesignChecklist#2]
https://github.com/FriendsOfEpub/eBookDesignChecklist/blob/dafcb93098b9c9e88e632adef2620787ddd76d4c/index.html#L73

Consider replacing with https://www.w3.org/TR/dpub-aria-1.0/#roles or relevant working link.

**Comment by JayPanoz** [comment]
Thanks for reporting that. 

After a quick check, this is the new link for this broken one: https://www.w3.org/TR/wai-aria-1.1/ ([Wayback Machine](https://web.archive.org/web/20171114115638/http://www.w3.org:80/TR/wai-aria/roles))

Commit on its way.
