### ISSUE TITLE
IDPF link redirects to APKB, consider replacing

### ISSUE THREAD

**Issue by jsarkis** [FriendsOfEpub/eBookDesignChecklist#3]
https://github.com/FriendsOfEpub/eBookDesignChecklist/blob/dafcb93098b9c9e88e632adef2620787ddd76d4c/index.html#L237

IDPF link redirects, consider replacing link with http://kb.daisy.org/publishing/ or http://kb.daisy.org/publishing/docs/css/color.html

**Comment by JayPanoz** [comment]
Thanks for pointing that, commit on its way.
